export const GET_ADRESSES = 'GET_ADRESSES';
export const GET_ADRESSES_PENDING = 'GET_ADRESSES_PENDING';
export const GET_ADRESSES_FULFILLED = 'GET_ADRESSES_FULFILLED';
export const GET_ADRESSES_REJECTED = 'GET_ADRESSES_REJECTED';

export const EDIT_ADRESSES_INPUT = 'EDIT_ADRESSES_INPUT';
export const CLEAR_ADRESSES_INPUT = 'CLEAR_ADRESSES_INPUT';

export const EDIT_FIAS_INPUT = 'EDIT_FIAS_INPUT';
export const CLEAR_FIAS_INPUT = 'CLEAR_FIAS_INPUT';

export const FOCUS_ADRESS_INPUT = 'FOCUS_ADRESS_INPUT';

export const STATUS_RED_ADRESS_ADN_FIAS_TEXT = 'STATUS_RED_ADRESS_ADN_FIAS_TEXT';
