export const GET_USERS = 'GET_USERS';
export const GET_USERS_PENDING = 'GET_USERS_PENDING';
export const GET_USERS_FULFILLED = 'GET_USERS_FULFILLED';
export const GET_USERS_REJECTED = 'GET_USERS_REJECTED';

export const DELETE_USER = 'DELETE_USER';
export const DELETE_USER_PENDING = 'DELETE_USER_PENDING';
export const DELETE_USER_FULFILLED = 'DELETE_USER_FULFILLED';
export const DELETE_USER_REJECTED = 'DELETE_USER_REJECTED';


export const SET_START_DATE = 'SET_START_DATE';
export const CLEAR_START_DATE = 'CLEAR_START_DATE';

export const SET_END_DATE = 'SET_END_DATE';
export const CLEAR_END_DATE = 'CLEAR_END_DATE';

export const SET_FIND_INPUT_FIO = 'SET_FIND_INPUT_FIO';
export const CLEAR_FIND_INPUT_FIO = 'CLEAR_FIND_INPUT_FIO';

export const SET_TELEPHONE_INPUT = 'SET_TELEPHONE_INPUT';
export const CLEAR_TELEPHONE_INPUT = 'CLEAR_TELEPHONE_INPUT';

export const SET_NEW_FIO_INPUT = 'SET_NEW_FIO_INPUT';
export const CLEAR_NEW_FIO_INPUT = 'CLEAR_NEW_FIO_INPUT';

export const FOCUS_NEW_FIO_INPUT = 'FOCUS_NEW_FIO_INPUT';

export const STATUS_RED_NEW_FIO_INPUT_TEXT = 'STATUS_RED_NEW_FIO_INPUT_TEXT';

export const POST_USER = 'POST_USER';
export const POST_USER_PENDING = 'POST_USER_PENDING';
export const POST_USER_FULFILLED = 'POST_USER_FULFILLED';
export const POST_USER_REJECTED = 'POST_USER_REJECTED';